---
- name: Install dependencies
  ansible.builtin.apt:
    name: "{{ filebeat_dependencies }}"
    state: present
    update_cache: true

- name: Configure Elastic APT repository
  ansible.builtin.deb822_repository:
    components: main
    name: elastic
    signed_by: "{{ filebeat_apt_signed_by }}"
    suites: stable
    uris: "{{ filebeat_apt_uris }}"

- name: Ensure filebeat package is installed
  ansible.builtin.apt:
    name: "{{ filebeat_package }}"
    state: "{{ filebeat_package_state }}"
    update_cache: true
  notify:
    - Restart filebeat

- name: Setup filebeat.yml
  ansible.builtin.template:
    dest: /etc/filebeat/filebeat.yml
    group: root
    mode: "0600"
    owner: root
    src: filebeat.yml.j2
  notify:
    - Restart filebeat

- name: Ensure filebeat is started and starts at boot
  ansible.builtin.service:
    enabled: true
    name: filebeat
    state: started
