---
- name: Install dependencies
  ansible.builtin.apt:
    name: "{{ filebeat_dependencies }}"
    state: present
    update_cache: true

- name: Add filebeat signing key
  ansible.builtin.apt_key:
    state: present
    url: "{{ filebeat_signing_key }}"

- name: Manage filebeat APT repository
  ansible.builtin.apt_repository:
    repo: "{{ filebeat_repository }}"
    state: "{{ 'absent' if filebeat_use_oss else 'present' }}"

- name: Manage filebeat OSS APT repository
  ansible.builtin.apt_repository:
    repo: "{{ filebeat_oss_repository }}"
    state: "{{ 'present' if filebeat_use_oss else 'absent' }}"

- name: Ensure filebeat package is installed
  ansible.builtin.apt:
    name: "{{ filebeat_package }}"
    state: "{{ filebeat_package_state }}"
    update_cache: true
  notify:
    - Restart filebeat

- name: Setup filebeat.yml
  ansible.builtin.template:
    dest: /etc/filebeat/filebeat.yml
    group: root
    mode: 0600
    owner: root
    src: filebeat.yml.j2
  notify:
    - Restart filebeat

- name: Ensure filebeat is started and starts at boot
  ansible.builtin.service:
    enabled: true
    name: filebeat
    state: started
